# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb163a877c456c5c1beddbd90255a99f2b6b130fe65797936bf7a67bf7d2a20fd364c5fb812137b9909998650fd8d5acc85a27def3dd04527e549b8377e02722

test:
  secret_key_base: 2d3d8f0738175bcbbec8acc1eafcd3e577fb8a7b066bd3bd9f62e6b4b7a680cdeae9eef48936501a8ffd4df18ca5e68acfdad6d6f9d88605090f24d224a2840a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
